Revert "Xext: shape: clean up Xinerama dispatch"
This reverts commit a57db845.

It breaks when building with -Dxinerama=false:

../Xext/shape.c: In function ‘ProcShapeRectangles’:
../Xext/shape.c:318:12: error: too few arguments to function
 ‘ShapeRectangles’; expected 2, have 1
  318 |     return ShapeRectangles(client);
      |            ^~~~~~~~~~~~~~~