Revert "os: move AbortServer() to os/utils.c"
This reverts commit 8e8bf639.

It failed to build if xf86bigfont was enabled:
../os/utils.c: In function ‘AbortServer’:
../os/utils.c:1555:5: error: implicit declaration of function
 ‘XF86BigfontCleanup’ [-Wimplicit-function-declaration]
 1555 |     XF86BigfontCleanup();
      |     ^~~~~~~~~~~~~~~~~~