xf86bigfont: Fix -Werror=missing-prototypes build failure
../Xext/xf86bigfont.c: At top level:
../Xext/xf86bigfont.c:683:1: error: no previous prototype for
 ‘XFree86BigfontExtensionInit’ [-Werror=missing-prototypes]
  683 | XFree86BigfontExtensionInit(void)
      | ^~~~~~~~~~~~~~~~~~~~~~~~~~~